title: Awesome Noodl
description: A curated list of awesome things related to Noodl. Maintained by The Low Code Foundation
email: richard@digitalbricks.io
url: https://awesome-noodl.com
author:
  name: Richard Osborne
  url: https://thelowcodefoundation.com

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
